apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alerts
  namespace: default
data:
  alert-rules.yml: |
    groups:
    - name: techcommerce_alerts
      interval: 30s
      rules:
      
      # Alert 1: Pod restarts (>3 in 10 min)
      - alert: HighPodRestartRate
        expr: rate(kube_pod_container_status_restarts_total[10m]) > 0.5
        for: 2m
        labels:
          severity: warning
          service: kubernetes
        annotations:
          summary: "High pod restart rate detected"
          description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has restarted more than 3 times in the last 10 minutes."
      
      # Alert 2: API response times (>2s for 5 min)
      - alert: SlowAPIResponse
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "API response time is too slow"
          description: "95th percentile API response time for {{ $labels.job }} is {{ $value }}s (threshold: 2s)"
      
      # Alert 3: Error rates (>5% for 5 min)
      - alert: HighErrorRate
        expr: |
          (
            sum(rate(http_requests_total{status=~"5.."}[5m])) by (job)
            /
            sum(rate(http_requests_total[5m])) by (job)
          ) * 100 > 5
        for: 5m
        labels:
          severity: critical
          service: api
        annotations:
          summary: "High error rate detected"
          description: "Service {{ $labels.job }} has error rate of {{ $value }}% (threshold: 5%)"
      
      # Alert 4: Disk usage (>85%)
      - alert: HighDiskUsage
        expr: |
          (
            (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_avail_bytes{mountpoint="/"})
            /
            node_filesystem_size_bytes{mountpoint="/"}
          ) * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: infrastructure
        annotations:
          summary: "High disk usage detected"
          description: "Disk usage on {{ $labels.instance }} is {{ $value }}% (threshold: 85%)"
      
      # Additional helpful alerts
      - alert: PodCrashLooping
        expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
        for: 5m
        labels:
          severity: critical
          service: kubernetes
        annotations:
          summary: "Pod is crash looping"
          description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is crash looping"
      
      - alert: HighMemoryUsage
        expr: |
          (
            container_memory_usage_bytes{container!=""}
            /
            container_spec_memory_limit_bytes{container!=""}
          ) * 100 > 90
        for: 5m
        labels:
          severity: warning
          service: kubernetes
        annotations:
          summary: "High memory usage detected"
          description: "Container {{ $labels.container }} in pod {{ $labels.pod }} is using {{ $value }}% of memory limit"
      
      - alert: HighCPUUsage
        expr: |
          (
            rate(container_cpu_usage_seconds_total{container!=""}[5m])
            /
            container_spec_cpu_quota{container!=""} * container_spec_cpu_period{container!=""}
          ) * 100 > 80
        for: 10m
        labels:
          severity: warning
          service: kubernetes
        annotations:
          summary: "High CPU usage detected"
          description: "Container {{ $labels.container }} in pod {{ $labels.pod }} is using {{ $value }}% of CPU limit"